title: Relaynet SDK

markdown: kramdown

baseurl: /relaynet-core-js
destination: ../build/docs
remote_theme: pmarsceill/just-the-docs@v0.2.7-r
color_scheme: dark

search_enabled: false

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
